import type { BetterAuthPluginDBSchema } from "better-auth";
export const bnplSchema = {
	bnplOrder: {
		modelName: "bnplOrder",
		fields: {
			userId: {
				type: "string",
				required: false,
				input: false,
				index: true,
				references: { model: "user", field: "id", onDelete: "set null" },
			},
			provider: { type: "string", required: true, input: false, index: true },
			orderReferenceId: { type: "string", required: true, unique: true, input: false },
			providerOrderId: { type: "string", required: false, input: false, index: true },
			providerCheckoutId: { type: "string", required: false, input: false },
			status: { type: "string", required: true, input: false },
			amountMinor: { type: "number", required: true, input: false },
			currency: { type: "string", required: true, input: false },
			paymentType: { type: "string", required: false, input: false },
			authorisedAt: { type: "date", required: false, input: false },
			capturedAt: { type: "date", required: false, input: false },
			capturedAmountMinor: { type: "number", required: true, defaultValue: 0, input: false },
			canceledAt: { type: "date", required: false, input: false },
			refundedAmountMinor: { type: "number", required: true, defaultValue: 0, input: false },
			rawData: { type: "string", required: false, input: false, returned: false },
			metadata: { type: "string", required: false, input: false },
			version: { type: "number", required: true, defaultValue: 0, input: false },
			createdAt: { type: "date", required: true, input: false },
			updatedAt: { type: "date", required: true, input: false },
		},
	},
	bnplWebhookEvent: {
		modelName: "bnplWebhookEvent",
		fields: {
			provider: { type: "string", required: true, input: false },
			providerOrderId: { type: "string", required: true, input: false, index: true },
			providerOrderReferenceId: { type: "string", required: false, input: false },
			eventKind: { type: "string", required: true, input: false },
			eventType: { type: "string", required: true, input: false },
			dedupKey: { type: "string", required: true, unique: true, input: false },
			receivedAt: { type: "date", required: true, input: false },
			rawData: { type: "string", required: false, input: false, returned: false },
			status: { type: "string", required: true, defaultValue: "received", input: false },
			attempts: { type: "number", required: true, defaultValue: 0, input: false },
			orderApplied: { type: "boolean", required: true, defaultValue: false, input: false },
			processedAt: { type: "date", required: false, input: false },
			lastError: { type: "string", required: false, input: false },
		},
	},
} satisfies BetterAuthPluginDBSchema;
